version: '3'
services:
  web:
    container_name: webapp
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - CWD=/usr/app/
      - NODE_ENV=development
      - LOG_LEVEL=debug
    ports:
      - "5000:5000"
