version: '3'
services:
  backend:
    container_name: webapp
    restart: always
    build:
      context: "."
      args:
        - BASE=/home/www-data
        - PORT=5000
    command: npm run start
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - NODE_ENV=development
      - LOG_LEVEL=debug